  0%|          | 0/250 [00:00<?, ?it/s]  0%|          | 1/250 [00:00<00:30,  8.15it/s]  1%|          | 2/250 [00:00<00:32,  7.70it/s]  1%|          | 3/250 [00:01<02:35,  1.59it/s]  2%|▏         | 4/250 [00:04<05:58,  1.46s/it]  2%|▏         | 5/250 [00:06<07:11,  1.76s/it]  2%|▏         | 6/250 [00:09<09:09,  2.25s/it]  3%|▎         | 7/250 [00:11<09:03,  2.24s/it]  3%|▎         | 8/250 [00:13<08:03,  2.00s/it]  4%|▎         | 9/250 [00:18<12:04,  3.01s/it]  4%|▍         | 10/250 [00:23<14:00,  3.50s/it]  4%|▍         | 11/250 [00:25<12:14,  3.07s/it]  5%|▍         | 12/250 [00:45<33:10,  8.36s/it]  5%|▌         | 13/250 [00:52<31:28,  7.97s/it]  6%|▌         | 14/250 [00:55<25:05,  6.38s/it]  6%|▌         | 15/250 [00:57<19:15,  4.92s/it]  6%|▋         | 16/250 [00:59<16:45,  4.30s/it]  7%|▋         | 17/250 [01:04<16:54,  4.35s/it]  7%|▋         | 18/250 [01:07<15:04,  3.90s/it]  8%|▊         | 19/250 [01:10<13:46,  3.58s/it]  8%|▊         | 20/250 [01:16<16:54,  4.41s/it]  8%|▊         | 21/250 [01:24<21:02,  5.51s/it]  9%|▉         | 22/250 [01:29<19:50,  5.22s/it]  9%|▉         | 23/250 [01:31<16:20,  4.32s/it] 10%|▉         | 24/250 [01:33<13:25,  3.56s/it] 10%|█         | 25/250 [01:36<13:31,  3.61s/it] 10%|█         | 26/250 [01:44<18:12,  4.88s/it] 11%|█         | 27/250 [01:53<22:34,  6.07s/it] 11%|█         | 28/250 [01:59<22:02,  5.96s/it] 12%|█▏        | 29/250 [02:06<23:38,  6.42s/it] 12%|█▏        | 30/250 [02:10<20:21,  5.55s/it] 12%|█▏        | 31/250 [02:30<36:54, 10.11s/it] 13%|█▎        | 32/250 [02:35<30:46,  8.47s/it] 13%|█▎        | 33/250 [02:41<27:35,  7.63s/it] 14%|█▎        | 34/250 [02:43<21:52,  6.08s/it] 14%|█▍        | 35/250 [02:45<17:39,  4.93s/it] 14%|█▍        | 36/250 [02:51<18:05,  5.07s/it] 15%|█▍        | 37/250 [02:55<17:00,  4.79s/it] 15%|█▌        | 38/250 [03:00<17:09,  4.86s/it] 16%|█▌        | 39/250 [03:10<22:13,  6.32s/it] 16%|█▌        | 40/250 [03:15<20:55,  5.98s/it] 16%|█▋        | 41/250 [03:20<19:24,  5.57s/it] 17%|█▋        | 42/250 [03:42<37:15, 10.75s/it] 17%|█▋        | 43/250 [03:52<35:58, 10.43s/it] 18%|█▊        | 44/250 [04:00<33:23,  9.73s/it] 18%|█▊        | 45/250 [04:04<27:34,  8.07s/it] 18%|█▊        | 46/250 [04:09<23:27,  6.90s/it] 19%|█▉        | 47/250 [04:13<21:16,  6.29s/it] 19%|█▉        | 48/250 [04:31<32:37,  9.69s/it] 20%|█▉        | 49/250 [04:34<25:42,  7.68s/it] 20%|██        | 50/250 [04:44<27:41,  8.31s/it] 20%|██        | 51/250 [05:07<42:11, 12.72s/it] 21%|██        | 52/250 [05:18<40:51, 12.38s/it] 21%|██        | 53/250 [05:40<49:56, 15.21s/it] 22%|██▏       | 54/250 [05:45<38:58, 11.93s/it] 22%|██▏       | 55/250 [05:58<40:28, 12.45s/it] 22%|██▏       | 56/250 [06:02<31:39,  9.79s/it] 23%|██▎       | 57/250 [06:05<25:35,  7.96s/it] 23%|██▎       | 58/250 [06:16<27:32,  8.60s/it] 24%|██▎       | 59/250 [06:19<22:44,  7.14s/it] 24%|██▎       | 59/250 [06:21<20:33,  6.46s/it]
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-94bfbd7604e9>", line 7, in <module>
    action = agent.get_action(states, evaluation)
  File "../src/agent.py", line 96, in get_action
    actions = self.actor(state)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "../src/networks.py", line 51, in call
    return policy * self.upper_bound
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 1164, in binary_op_wrapper
    return func(x, y, name=name)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 1496, in _mul_dispatch
    return multiply(x, y, name=name)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 518, in multiply
    return gen_math_ops.mul(x, y, name)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 6072, in mul
    return mul_eager_fallback(
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 6095, in mul_eager_fallback
    _attrs = ("T", _attr_T)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2045, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1170, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 1461, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 708, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 754, in getmodule
    os.path.realpath(f)] = module.__name__
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/posixpath.py", line 391, in realpath
    path, ok = _joinrealpath(filename[:0], filename, {})
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/posixpath.py", line 425, in _joinrealpath
    if not islink(newpath):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/posixpath.py", line 167, in islink
    st = os.lstat(path)
KeyboardInterrupt
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-94bfbd7604e9>", line 7, in <module>
    action = agent.get_action(states, evaluation)
  File "../src/agent.py", line 96, in get_action
    actions = self.actor(state)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "../src/networks.py", line 51, in call
    return policy * self.upper_bound
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 1164, in binary_op_wrapper
    return func(x, y, name=name)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 1496, in _mul_dispatch
    return multiply(x, y, name=name)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 518, in multiply
    return gen_math_ops.mul(x, y, name)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 6072, in mul
    return mul_eager_fallback(
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 6095, in mul_eager_fallback
    _attrs = ("T", _attr_T)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2045, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3338, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3435, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2047, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1436, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1336, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1193, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1151, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 451, in find_recursion
    return len(records), 0
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2045, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1170, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 1461, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 708, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 754, in getmodule
    os.path.realpath(f)] = module.__name__
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/posixpath.py", line 391, in realpath
    path, ok = _joinrealpath(filename[:0], filename, {})
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/posixpath.py", line 425, in _joinrealpath
    if not islink(newpath):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/posixpath.py", line 167, in islink
    st = os.lstat(path)
KeyboardInterrupt
