loading weights
945736
3000
[1.07478544 0.93044417]
  0%|          | 0/250 [00:00<?, ?it/s][-385.34238009956414]
  0%|          | 1/250 [00:00<02:58,  1.39it/s][-385.34238009956414, 280.28589674847444]
  1%|          | 2/250 [00:01<02:21,  1.76it/s][-385.34238009956414, 280.28589674847444, 173.44945065583838]
  1%|          | 3/250 [00:03<05:08,  1.25s/it][-385.34238009956414, 280.28589674847444, 173.44945065583838, 234.42018775028558]
  2%|▏         | 4/250 [00:03<03:48,  1.08it/s][-385.34238009956414, 280.28589674847444, 173.44945065583838, 234.42018775028558, 254.61223807572966]
  2%|▏         | 5/250 [00:04<03:42,  1.10it/s][-385.34238009956414, 280.28589674847444, 173.44945065583838, 234.42018775028558, 254.61223807572966, 53.12121165671877]
  2%|▏         | 6/250 [00:04<02:45,  1.48it/s][-385.34238009956414, 280.28589674847444, 173.44945065583838, 234.42018775028558, 254.61223807572966, 53.12121165671877, 283.8451536771538]
  3%|▎         | 7/250 [00:05<02:18,  1.76it/s][-385.34238009956414, 280.28589674847444, 173.44945065583838, 234.42018775028558, 254.61223807572966, 53.12121165671877, 283.8451536771538, 250.3370397876007]
  3%|▎         | 8/250 [00:05<02:00,  2.01it/s][-385.34238009956414, 280.28589674847444, 173.44945065583838, 234.42018775028558, 254.61223807572966, 53.12121165671877, 283.8451536771538, 250.3370397876007, 272.1203954271827]
  4%|▎         | 9/250 [00:05<01:48,  2.22it/s][-385.34238009956414, 280.28589674847444, 173.44945065583838, 234.42018775028558, 254.61223807572966, 53.12121165671877, 283.8451536771538, 250.3370397876007, 272.1203954271827, 250.55121481242873]
  4%|▍         | 10/250 [00:07<03:46,  1.06it/s][-385.34238009956414, 280.28589674847444, 173.44945065583838, 234.42018775028558, 254.61223807572966, 53.12121165671877, 283.8451536771538, 250.3370397876007, 272.1203954271827, 250.55121481242873, 145.13523704403136]
  4%|▍         | 11/250 [00:09<04:38,  1.16s/it][-385.34238009956414, 280.28589674847444, 173.44945065583838, 234.42018775028558, 254.61223807572966, 53.12121165671877, 283.8451536771538, 250.3370397876007, 272.1203954271827, 250.55121481242873, 145.13523704403136, 252.95972978887215]
  5%|▍         | 12/250 [00:09<03:39,  1.08it/s][-385.34238009956414, 280.28589674847444, 173.44945065583838, 234.42018775028558, 254.61223807572966, 53.12121165671877, 283.8451536771538, 250.3370397876007, 272.1203954271827, 250.55121481242873, 145.13523704403136, 252.95972978887215, 256.61381561982273]
  5%|▌         | 13/250 [00:10<02:58,  1.33it/s][-385.34238009956414, 280.28589674847444, 173.44945065583838, 234.42018775028558, 254.61223807572966, 53.12121165671877, 283.8451536771538, 250.3370397876007, 272.1203954271827, 250.55121481242873, 145.13523704403136, 252.95972978887215, 256.61381561982273, 274.5243312815057]
  6%|▌         | 14/250 [00:10<02:29,  1.58it/s][-385.34238009956414, 280.28589674847444, 173.44945065583838, 234.42018775028558, 254.61223807572966, 53.12121165671877, 283.8451536771538, 250.3370397876007, 272.1203954271827, 250.55121481242873, 145.13523704403136, 252.95972978887215, 256.61381561982273, 274.5243312815057, 308.5122867023355]
  6%|▌         | 15/250 [00:11<02:16,  1.72it/s][-385.34238009956414, 280.28589674847444, 173.44945065583838, 234.42018775028558, 254.61223807572966, 53.12121165671877, 283.8451536771538, 250.3370397876007, 272.1203954271827, 250.55121481242873, 145.13523704403136, 252.95972978887215, 256.61381561982273, 274.5243312815057, 308.5122867023355, 242.009018258149]
  6%|▋         | 16/250 [00:12<02:47,  1.39it/s]  6%|▋         | 16/250 [00:12<02:58,  1.31it/s]
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-7f9108cd8061>", line 7, in <module>
    action = agent.get_action(states, evaluation)
  File "../src/agent.py", line 96, in get_action
    actions = self.actor(state)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "../src/networks.py", line 49, in call
    policy = self.policy(policy)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/keras/layers/core.py", line 1207, in call
    return core_ops.dense(
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/keras/layers/ops/core.py", line 53, in dense
    outputs = gen_math_ops.mat_mul(inputs, kernel)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5527, in mat_mul
    _result = pywrap_tfe.TFE_Py_FastPathExecute(
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2045, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1170, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 1461, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 708, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 754, in getmodule
    os.path.realpath(f)] = module.__name__
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/posixpath.py", line 392, in realpath
    return abspath(path)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/posixpath.py", line 381, in abspath
    return normpath(path)
KeyboardInterrupt
