/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/gym/logger.py:30: UserWarning: [33mWARN: Box bound precision lowered by casting to float32[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
  0%|          | 0/100000 [00:00<?, ?it/s]  0%|          | 1/100000 [00:00<5:28:12,  5.08it/s]  0%|          | 3/100000 [00:00<5:07:13,  5.42it/s]  0%|          | 4/100000 [00:02<22:30:51,  1.23it/s]  0%|          | 5/100000 [00:03<24:20:33,  1.14it/s]  0%|          | 6/100000 [00:04<26:57:28,  1.03it/s]  0%|          | 7/100000 [00:05<24:02:21,  1.16it/s]  0%|          | 8/100000 [00:06<22:22:23,  1.24it/s]  0%|          | 9/100000 [00:06<21:37:53,  1.28it/s]  0%|          | 10/100000 [00:08<29:41:47,  1.07s/it]  0%|          | 11/100000 [00:09<26:36:03,  1.04it/s]  0%|          | 12/100000 [00:09<22:14:37,  1.25it/s]  0%|          | 13/100000 [00:10<24:26:16,  1.14it/s]  0%|          | 14/100000 [00:11<27:34:36,  1.01it/s]  0%|          | 15/100000 [00:12<24:28:50,  1.13it/s]  0%|          | 16/100000 [00:13<26:07:00,  1.06it/s]  0%|          | 17/100000 [00:14<24:48:17,  1.12it/s]  0%|          | 18/100000 [00:15<29:24:03,  1.06s/it]  0%|          | 19/100000 [00:16<29:17:00,  1.05s/it]  0%|          | 20/100000 [00:19<38:32:48,  1.39s/it]  0%|          | 21/100000 [00:20<38:07:37,  1.37s/it]  0%|          | 22/100000 [00:31<115:19:15,  4.15s/it]  0%|          | 23/100000 [00:32<96:09:21,  3.46s/it]   0%|          | 24/100000 [00:36<93:42:21,  3.37s/it]  0%|          | 25/100000 [00:39<95:51:30,  3.45s/it]  0%|          | 26/100000 [00:42<88:06:32,  3.17s/it]  0%|          | 27/100000 [00:47<102:14:10,  3.68s/it]  0%|          | 28/100000 [00:49<92:42:55,  3.34s/it]   0%|          | 29/100000 [00:54<103:18:43,  3.72s/it]  0%|          | 30/100000 [00:59<115:09:55,  4.15s/it]  0%|          | 31/100000 [01:05<131:19:52,  4.73s/it]  0%|          | 32/100000 [01:18<204:06:18,  7.35s/it]  0%|          | 33/100000 [01:25<194:46:19,  7.01s/it]  0%|          | 34/100000 [01:32<194:13:50,  6.99s/it]  0%|          | 35/100000 [01:45<251:20:13,  9.05s/it]  0%|          | 36/100000 [01:52<231:11:24,  8.33s/it]  0%|          | 37/100000 [02:06<280:56:01, 10.12s/it]  0%|          | 38/100000 [02:11<235:41:27,  8.49s/it]  0%|          | 39/100000 [02:37<380:28:44, 13.70s/it]  0%|          | 40/100000 [02:47<349:07:29, 12.57s/it]  0%|          | 41/100000 [02:55<307:45:19, 11.08s/it]  0%|          | 42/100000 [03:04<295:47:11, 10.65s/it]  0%|          | 43/100000 [03:12<274:08:36,  9.87s/it]  0%|          | 44/100000 [03:19<244:54:22,  8.82s/it]  0%|          | 45/100000 [03:28<250:28:51,  9.02s/it]  0%|          | 46/100000 [03:36<240:34:33,  8.66s/it]  0%|          | 47/100000 [03:42<217:52:12,  7.85s/it]  0%|          | 47/100000 [03:48<134:48:01,  4.86s/it]
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-8f485f7f2afa>", line 7, in <module>
    action = agent.get_action(states)
  File "../src/agent.py", line 73, in get_action
    actions, _ = self.actor.get_action_log_probs(state, reparameterization_trick=False)
  File "../src/networks.py", line 83, in get_action_log_probs
    log_probs = normal_distr.log_prob(actions) - tf.math.log(1-tf.math.pow(action,2)+self.noise)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py", line 866, in log_prob
    return self._call_log_prob(value, name, **kwargs)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py", line 844, in _call_log_prob
    with self._name_scope(name):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py", line 1314, in _name_scope
    with tf.name_scope(name) as scope:
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6642, in __enter__
    ctx.scope_name = scope_name
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 835, in scope_name
    self._thread_local_data.scope_name = s
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2045, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1170, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 1461, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 708, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 751, in getmodule
    f = getabsfile(module)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 721, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/posixpath.py", line 381, in abspath
    return normpath(path)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/posixpath.py", line 358, in normpath
    if comp in (empty, dot):
KeyboardInterrupt
