/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/gym/logger.py:30: UserWarning: [33mWARN: Box bound precision lowered by casting to float32[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
  0%|          | 0/100000 [00:00<?, ?it/s]  0%|          | 2/100000 [00:00<1:46:37, 15.63it/s]  0%|          | 4/100000 [00:00<1:37:21, 17.12it/s]  0%|          | 6/100000 [00:02<12:31:07,  2.22it/s]  0%|          | 7/100000 [00:03<17:40:11,  1.57it/s]  0%|          | 8/100000 [00:03<17:51:50,  1.55it/s]  0%|          | 9/100000 [00:04<16:41:47,  1.66it/s]  0%|          | 10/100000 [00:05<19:01:55,  1.46it/s]  0%|          | 11/100000 [00:07<28:57:17,  1.04s/it]  0%|          | 12/100000 [00:08<30:13:55,  1.09s/it]  0%|          | 13/100000 [00:09<27:08:57,  1.02it/s]  0%|          | 14/100000 [00:10<33:16:11,  1.20s/it]  0%|          | 15/100000 [00:12<40:21:56,  1.45s/it]  0%|          | 16/100000 [00:14<42:28:35,  1.53s/it]  0%|          | 17/100000 [00:15<39:27:17,  1.42s/it]  0%|          | 18/100000 [00:18<47:22:29,  1.71s/it]  0%|          | 19/100000 [00:19<40:56:57,  1.47s/it]  0%|          | 20/100000 [00:22<59:41:13,  2.15s/it]  0%|          | 21/100000 [00:26<74:48:55,  2.69s/it]  0%|          | 22/100000 [00:32<99:29:05,  3.58s/it]  0%|          | 23/100000 [00:39<125:39:31,  4.52s/it]  0%|          | 24/100000 [01:21<437:00:37, 15.74s/it]  0%|          | 25/100000 [02:05<679:18:36, 24.46s/it]  0%|          | 25/100000 [02:19<155:28:39,  5.60s/it]
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-8f485f7f2afa>", line 11, in <module>
    agent.learn()
  File "../src/agent.py", line 115, in learn
    actor_gradient = tape.gradient(actor_loss, self.actor.trainable_variables)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/eager/backprop.py", line 1080, in gradient
    flat_grad = imperative_grad.imperative_grad(
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/eager/imperative_grad.py", line 71, in imperative_grad
    return pywrap_tfe.TFE_Py_TapeGradient(
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/eager/backprop.py", line 162, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/ops/math_grad.py", line 1694, in _MatMulGrad
    grad_a = gen_math_ops.mat_mul(grad, b, transpose_b=True)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5527, in mat_mul
    _result = pywrap_tfe.TFE_Py_FastPathExecute(
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2045, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1170, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 1461, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 708, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 751, in getmodule
    f = getabsfile(module)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 720, in getabsfile
    _filename = getsourcefile(object) or getfile(object)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 705, in getsourcefile
    if os.path.exists(filename):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
KeyboardInterrupt
