  0%|          | 0/250 [00:00<?, ?it/s]  0%|          | 1/250 [00:02<08:29,  2.05s/it]  1%|          | 2/250 [00:03<08:11,  1.98s/it]  1%|          | 3/250 [00:04<06:19,  1.54s/it]  2%|▏         | 4/250 [00:09<11:02,  2.70s/it]  2%|▏         | 5/250 [00:12<10:56,  2.68s/it]  2%|▏         | 6/250 [00:14<09:59,  2.46s/it]  3%|▎         | 7/250 [00:17<10:37,  2.63s/it]  3%|▎         | 8/250 [00:19<09:46,  2.42s/it]  4%|▎         | 9/250 [00:21<09:20,  2.32s/it]  4%|▍         | 10/250 [00:23<09:26,  2.36s/it]  4%|▍         | 11/250 [00:25<09:17,  2.33s/it]  5%|▍         | 12/250 [00:32<14:08,  3.57s/it]  5%|▌         | 13/250 [00:34<12:51,  3.26s/it]  6%|▌         | 14/250 [00:39<14:38,  3.72s/it]  6%|▌         | 15/250 [00:55<28:43,  7.33s/it]  6%|▋         | 16/250 [01:06<32:58,  8.45s/it]  7%|▋         | 17/250 [01:27<47:38, 12.27s/it]  7%|▋         | 18/250 [01:35<42:11, 10.91s/it]  7%|▋         | 18/250 [01:53<24:26,  6.32s/it]
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-94bfbd7604e9>", line 11, in <module>
    agent.learn()
  File "../src/agent.py", line 124, in learn
    critic_gradient = tape.gradient(critic_loss,
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/eager/backprop.py", line 1080, in gradient
    flat_grad = imperative_grad.imperative_grad(
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/eager/imperative_grad.py", line 71, in imperative_grad
    return pywrap_tfe.TFE_Py_TapeGradient(
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/eager/backprop.py", line 162, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/ops/math_grad.py", line 1694, in _MatMulGrad
    grad_a = gen_math_ops.mat_mul(grad, b, transpose_b=True)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5527, in mat_mul
    _result = pywrap_tfe.TFE_Py_FastPathExecute(
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2045, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1170, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 1461, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 708, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 751, in getmodule
    f = getabsfile(module)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 720, in getabsfile
    _filename = getsourcefile(object) or getfile(object)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 696, in getsourcefile
    filename = getfile(object)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 654, in getfile
    def getfile(object):
KeyboardInterrupt
